/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.monitoringenergirumah.Service.SistemMonitoring;
import com.mycompany.monitoringenergirumah.Model.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class TambahPerangkat extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TambahPerangkat.class.getName());

    private Perangkat parent;
    private SistemMonitoring sistem;
    private PerangkatListrik perangkatEdit = null; 

    // ========================================================
    // CONSTRUCTOR 1: KHUSUS UNTUK MENAMBAH PERANGKAT BARU
    // (Pasti errornya karena bagian ini hilang/tertimpa)
    // ========================================================
    public TambahPerangkat(Perangkat parent, SistemMonitoring sistem) {
        initComponents();
        this.parent = parent;
        this.sistem = sistem;
    }

    // ========================================================
    // CONSTRUCTOR 2: KHUSUS UNTUK MENGEDIT PERANGKAT
    // ========================================================
    public TambahPerangkat(Perangkat parent, SistemMonitoring sistem, PerangkatListrik p) {
        initComponents();
        this.parent = parent;
        this.sistem = sistem;
        this.perangkatEdit = p;
        
        if (p.getTanggalPemasangan() != null) {
            java.time.LocalDate ld = p.getTanggalPemasangan();
            java.util.Date date = java.sql.Date.valueOf(ld);
            jDateChooser1.setDate(date);
        }

        // Ubah judul form
        jLabel1.setText("Edit Perangkat");
        
        // Kunci jenis perangkat
        pilihJenis.setSelectedItem(p.getClass().getSimpleName());
        pilihJenis.setEnabled(false);

        // Isi form dengan data lama (UBAH BAGIAN INI)
        comboboxLokasi.setSelectedItem(p.getNama()); // Memilih lokasi di ComboBox
        txtDaya.setText(String.valueOf((int) p.getDaya()));
        txtLamaPemakaian.setText(String.valueOf(p.getLamaPemakaian()));
        
        // Khusus untuk AC
        if (p instanceof AC) {
            txtCop.setText(String.valueOf(((AC) p).getCop()));
        } else {
            txtCop.setEnabled(false);
        }
    }
    
    private void hitungEstimasi() {
        try {
            // 1. Mengambil teks dari inputan dengan variabel baru
            String jenis = pilihJenis.getSelectedItem().toString(); 
            String teksDaya = txtDaya.getText();                
            String teksWaktu = txtLamaPemakaian.getText();               

            // 2. Kembalikan ke 0 jika input kosong atau jenis belum dipilih
            if (jenis.equals("Pilih Jenis Perangkat") || teksDaya.trim().isEmpty() || teksWaktu.trim().isEmpty()) {
                lblEnergi.setText("0.00 kWh"); 
                lblHarga.setText("Rp 0");     
                return;
            }

            double daya = Double.parseDouble(teksDaya);
            double waktu = Double.parseDouble(teksWaktu);

            com.mycompany.monitoringenergirumah.Model.PerangkatListrik perangkatSementara = null;

            // 3. Kalkulasi menggunakan objek dummy sesuai jenisnya
            if (jenis.equals("AC")) {
                double cop = 3.0; 
                if (!txtCop.getText().isEmpty()) { 
                    cop = Double.parseDouble(txtCop.getText()); 
                }
                perangkatSementara = new com.mycompany.monitoringenergirumah.Model.AC("Estimasi", (int) daya, waktu, cop);
                
            } else if (jenis.equals("Lampu")) {
                perangkatSementara = new com.mycompany.monitoringenergirumah.Model.Lampu("Estimasi", (int) daya, waktu);
                
            } else if (jenis.equals("Televisi")) {
                perangkatSementara = new com.mycompany.monitoringenergirumah.Model.Televisi("Estimasi", (int) daya, waktu);
            }

            // 4. Output ke Label Energi dan Harga
            if (perangkatSementara != null) {
                double energi = perangkatSementara.hitungEnergi();
                double biaya = sistem.getKalkulator().hitungBiayaDenganPajak(energi);

                lblEnergi.setText(String.format("%.2f kWh", energi)); 
                lblHarga.setText(String.format("Rp %,.0f", biaya));  
            }

        } catch (NumberFormatException e) {
            lblEnergi.setText("0.00 kWh"); 
            lblHarga.setText("Rp 0");     
        } catch (Exception e) {
            lblEnergi.setText("Error");    
            lblHarga.setText("Error");    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pilihJenis = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDaya = new javax.swing.JTextField();
        txtLamaPemakaian = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblEnergi = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCop = new javax.swing.JTextField();
        comboboxLokasi = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tambah Perangkat Baru");

        pilihJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Perangkat", "Lampu", "AC", "Televisi" }));
        pilihJenis.setToolTipText("");

        jLabel2.setText("Jenis Perangkat");

        jLabel3.setText("Lokasi Pemasangan");

        jLabel4.setText("Daya (W)");

        jLabel5.setText("Lama Pemakaian (Jam)");

        txtDaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDayaKeyReleased(evt);
            }
        });

        txtLamaPemakaian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLamaPemakaianKeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Estimasi Energi & Biaya");

        lblEnergi.setText("0.00 kWh");

        lblHarga.setText(" Rp 0");

        jLabel10.setText("per hari");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblEnergi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lblHarga))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnergi)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Batal");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Nilai COP");

        txtCop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCopKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCop, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        comboboxLokasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masukkan Lokasi", "Kamar Tidur", "Ruang Tamu", "Kamar Mandi", "Dapur" }));

        jLabel8.setText("Tanggal Pemasangan (DD/MM/YYYY)");

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilihJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(txtDaya, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtLamaPemakaian)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboboxLokasi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pilihJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLamaPemakaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        String jenis = pilihJenis.getSelectedItem().toString();
        if (jenis.equals("Pilih Jenis Perangkat")) {
            JOptionPane.showMessageDialog(this, "Silakan pilih jenis perangkat!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String lokasi = comboboxLokasi.getSelectedItem().toString();
        if (lokasi.equals("Masukkan Lokasi")) {
            JOptionPane.showMessageDialog(this, "Silakan pilih lokasi pemasangan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.util.Date tanggalPilih = jDateChooser1.getDate();
        if (tanggalPilih == null) {
            JOptionPane.showMessageDialog(this, "Silakan pilih tanggal pemasangan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.time.LocalDate tanggalInput = tanggalPilih.toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();

        double daya  = Double.parseDouble(txtDaya.getText());
        double waktu = Double.parseDouble(txtLamaPemakaian.getText());

        // ── MODE EDIT ──
        if (perangkatEdit != null) {
            perangkatEdit.setNama(lokasi);
            perangkatEdit.setDaya((int) daya);
            perangkatEdit.setLamaPemakaian(waktu);
            perangkatEdit.setTanggalPemasangan(tanggalInput);

            if (perangkatEdit instanceof AC && !txtCop.getText().isEmpty()) {
                ((AC) perangkatEdit).setCop(Double.parseDouble(txtCop.getText()));
            }

            JOptionPane.showMessageDialog(this, "Perangkat berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            parent.refreshData(); // ← panggil refreshData setelah edit
            this.dispose();
            return; // ← stop, jangan lanjut ke mode tambah
        }

        // ── MODE TAMBAH ──
        PerangkatListrik perangkatBaru = null;

        if (jenis.equals("AC")) {
            double cop = 3.0;
            if (!txtCop.getText().isEmpty()) cop = Double.parseDouble(txtCop.getText());
            perangkatBaru = new AC(lokasi, (int) daya, waktu, cop);
        } else if (jenis.equals("Lampu")) {
            perangkatBaru = new Lampu(lokasi, (int) daya, waktu);
        } else if (jenis.equals("Televisi")) {
            perangkatBaru = new Televisi(lokasi, (int) daya, waktu);
        }

        if (perangkatBaru != null) {
            perangkatBaru.setTanggalPemasangan(tanggalInput);
            sistem.tambahPerangkat(perangkatBaru);

            JOptionPane.showMessageDialog(this, "Perangkat berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            parent.refreshData(); // ← ganti dari tampilkanData()
            this.dispose();
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Daya, Waktu, dan COP harus angka!", "Error Input", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDayaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDayaKeyReleased
        hitungEstimasi();
    }//GEN-LAST:event_txtDayaKeyReleased

    private void txtLamaPemakaianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLamaPemakaianKeyReleased
        hitungEstimasi();
    }//GEN-LAST:event_txtLamaPemakaianKeyReleased

    private void txtCopKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCopKeyReleased
        hitungEstimasi();
    }//GEN-LAST:event_txtCopKeyReleased

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxLokasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEnergi;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JComboBox<String> pilihJenis;
    private javax.swing.JTextField txtCop;
    private javax.swing.JTextField txtDaya;
    private javax.swing.JTextField txtLamaPemakaian;
    // End of variables declaration//GEN-END:variables
}
